language: ruby
rvm: 2.0.0

branches:
  only:
  - master

before_script:
  # http://projectpoppycock.com/unit-testing-with-angularjs-grunt-karma-and-travisci/
  - 'npm install -g grunt-cli'
  
  - git config --global user.name "Travis CI"
  - git remote set-url origin https://Maltretieren:${GH_TOKEN}@github.com/Maltretieren/maltretieren.github.com.git

script: phantomjs /tests/helloworld.js

env:
  global:
    secure: e7qb+HWe8cE7z7LVFCHqvCPCFyHRSRIzKYmUZHLfbaHOxE8e6K17eqSPFRIaBRYtEgjlIrx0OZe8Yh5uXehR9IiGRU3A4BlbiUDt0UClfIkplxf2coUMkAzWTa9kMDcErOY7GGBcv66vqKYC+III8Q+cNvyLkJXCZaNUYPhrGuE=

notifications:
  email: true
